name: CI
on: pull_request
defaults:
  run:
    shell: bash
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
jobs:
  lint:
    name: Runs lint
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install npm modules
        run: npm install
      - name: Exec lint
        run: npm run lint

  format:
    name: Runs prettier
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install npm modules
        run: npm install
      - name: Exec prettier
        run: npm run format-check

  test:
    name: Runs test
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install npm modules
        run: npm install
      - name: Exec prettier
        run: npm test
